### ISSUE TITLE
User-specified Installer Doesn't Open

### ISSUE THREAD

**Issue by howyay** [flathub/com.github.corna.Vivado#1]
# Context 
I'm trying to install an archived version of Xilinx Vivado (2020.2) because the new ML version are simply too costly in storage space to make any sense.

# Steps to Reproduce
1. Download any version of Linux unified installer from Xilinx website
2. chmod +x and make sure the installer is in a folder accessible by this flatpak
3. Click on the "Xilinx Vivado" shortcut created by this flatpak
4. Be warned "No Vivado is installed, do you want to install now?"
5. Click "Yes"
6. Choose the downloaded installer

# Expected Behaviour
1. The installer should open 

# Actual Behaviour
1. Nothing happens after choosing the installer

# Additional Details
It does work when I put in my credentials and download directly using this flatpak. (but I didn't proceed because ML is too big)

I suspected that an older installer may have operated differently than the latest version, but I tried downloading the latest installer myself, and it still didn't work.

I'm currently working around this by manually specifying the installation path to the path detected by this flatpak, but I also fear that by doing this I may have circumvented some sandboxing mechanism that prevented Xilinx software from polluting my computer.

**Comment by corna** [comment]
That's strange, as I use Vivado 2020.2 as well and I never had any issue.

Can you try again by running this flatpak from the terminal (`flatpak run com.github.corna.Vivado`) and posting here the output?

Btw, the step 2 is not necessary (the helper scripts automatically add the executable flag and, thanks to the xdg-desktop-portal magic, the installer can be anywhere on your system).

**Comment by howyay** [comment]
Thank you for the quick response!

I have concluded that this is most certainly an issue with my own setup, after some further investigation.

Faulty file permission on `/usr/share/fusermount3` also cause an identical issue for all other flatpaks too. Symptomized by the same lack of "access" to user directories. I fixed it by `chmod o+x` on said executable for other flatpaks.

I got some free time this afternoon, so I'm going to reinstall Vivado and verify my suspicion.

**Comment by howyay** [comment]
I've confirmed that was the root cause, the installer opened without any problem.

For more context, I'm using openSUSE and the `Secure` file permssion setting in YaST security center removed executable permissions for others on both `/usr/bin/fusermount` and `/usr/bin/fusermount3`, the first pervented flatpak installation but the second was symptomized a lot more inconspicuously like this Issue.

Thank you for your time and this convenient tool!

**Comment by corna** [comment]
Great, glad you solved it quickly!
