### ISSUE TITLE
Remove submodule

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.github.corna.Vivado#7]
We will be blocking non Flathub and non Flatpak submodules.

Since these are icons, please remove the submodule and use it directly as a git source in the manifest.

**Comment by corna** [comment]
Done (#8), however the linter fails with "appid-uses-code-hosting-domain: github.com"
Should I open a PR to add an exception in [flathub-infra/flatpak-builder-lint](https://github.com/flathub-infra/flatpak-builder-lint)? This project was created in 2021, before the above rule.

**Comment by bbhtt** [comment]
Yes please do, looks like we missed this when grandfathering the exceptions for that error.

**Comment by corna** [comment]
Done

**Comment by corna** [comment]
Fixed in 6c28e79
